COMPONENT=SenderAppC



#change sense channel   11~26
CC2420_CHANNEL=12 

#change the transmit power
CFLAGS += -DD2420_DEF_REPOWER=10

#change the message_t size
#CFLAGS += -D'TOSH_DATA_LENGTH=48'



include $(MAKERULES)

